const data = {
  products: [
    {
      _id: 1,
      name: "Nordic Chair",
      slug: "Nordic Chair",
      countInStock: 5,
      price: 70.0,
      image: "https://untree.co/demos/furni/images/product-3.png",
      description: 'high quality product',
    },
    {
      _id: 2,
      name: "Light Blue Soft Armchair",
      slug: "Light Blue Soft Armchair",
      countInStock: 5,
      price: 78.0,
      image: "https://www.freepnglogos.com/uploads/furniture-png/furniture-png-transparent-furniture-images-pluspng-15.png",
      description: 'high quality product',
    },
    {
      _id: 3,
      name: "Dark Blue Couch Sofa",
      slug: "Dark Blue Couch Sofa",
      countInStock: 5,
      price: 43.0,
      image: "https://png.pngtree.com/png-clipart/20220810/ourmid/pngtree-modern-single-blue-couch-sofa-interior-furniture-transparant-background-png-image_6105949.png",
      description: 'high quality product',
    },
    {
      _id: 4,
      name: "Kruzo Aero Chair",
      slug: "Kruzo Aero Chair",
      countInStock: 5,
      price: 77.0,
      image: "https://untree.co/demos/furni/images/product-2.png",
      description: 'high quality product',
    },
    {
      _id: 5,
      name: "Single Blue Couch Sofa",
      slug: "Single Blue Couch Sofa",
      countInStock: 5,
      price: 50.0,
      image: "https://png.pngtree.com/png-clipart/20220715/ourmid/pngtree-modern-single-blue-couch-sofa-interior-furniture-transparant-background-png-image_5967529.png",
      description: 'high quality product',
    },
    {
      _id: 6,
      name: "Ergonomic Chair",
      slug: "Ergonomic Chair",
      countInStock: 5,
      price: 79.0,
      image: "https://untree.co/demos/furni/images/product-1.png",
      description: 'high quality product',
    },
    {
      _id: 7,
      name: "Tufted Round Chair",
      slug: "Tufted Round Chair",
      countInStock: 5,
      price: 72.0,
      image: "https://www.freepnglogos.com/uploads/furniture-png/furniture-png-transparent-images-png-only-34.png",
      description: 'high quality product',
    },
    {
      _id: 8,
      name: "Fabric Armchair Soft Cushion",
      slug: "Fabric Armchair Soft Cushion",
      countInStock: 5,
      price: 50.0,
      image: "https://static.vecteezy.com/system/resources/previews/011/794/199/original/fabric-armchair-soft-cushion-with-metal-leg-3d-rendering-modern-interior-design-for-living-room-free-png.png",
      description: 'high quality product',
    },
    
  ],
};

export default data;
